version: '3.8'

services:
  # PostgreSQL 数据库 + PostGIS 扩展
  postgres:
    image: postgis/postgis:15-3.3
    container_name: telegram-bot-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-telegram_bot_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - telegram-bot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-telegram_bot_db}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis 缓存和消息队列
  redis:
    image: redis:7-alpine
    container_name: telegram-bot-redis
    # 移除 --requirepass 参数，因为我们没有在.env中设置密码
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
      - ./scripts/redis.conf:/etc/redis/redis.conf:ro
    networks:
      - telegram-bot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI 应用服务
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: telegram-bot-api
    environment:
      - DEBUG=${DEBUG:-True}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-telegram_bot_db}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # S3 配置
      - STORAGE_BACKEND=${STORAGE_BACKEND:-local}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - AWS_S3_PUBLIC_READ=${AWS_S3_PUBLIC_READ:-false}
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - .:/app
      - ./storage:/app/storage
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - telegram-bot-network
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        python -c 'import time; time.sleep(10)' &&
        echo 'Running database migrations...' &&
        alembic upgrade head &&
        echo 'Starting FastAPI server...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  # Telegram Bot 服务
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: telegram-bot-service
    environment:
      - DEBUG=${DEBUG:-True}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-telegram_bot_db}
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - API_BASE_URL=http://api:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # S3 配置
      - STORAGE_BACKEND=${STORAGE_BACKEND:-local}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - AWS_S3_PUBLIC_READ=${AWS_S3_PUBLIC_READ:-false}
    volumes:
      - .:/app
      - ./storage:/app/storage
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
      - api
    networks:
      - telegram-bot-network
    restart: unless-stopped
    command: python app/bot/main.py

  # Celery Worker 异步任务处理
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: telegram-bot-celery-worker
    environment:
      - DEBUG=${DEBUG:-True}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-telegram_bot_db}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # S3 配置
      - STORAGE_BACKEND=${STORAGE_BACKEND:-local}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - AWS_S3_PUBLIC_READ=${AWS_S3_PUBLIC_READ:-false}
    volumes:
      - .:/app
      - ./storage:/app/storage
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - telegram-bot-network
    restart: unless-stopped
    command: celery -A app.core.celery_app worker --loglevel=info -Q celery,ai_moderation,notifications

  # Celery Beat 定时任务调度
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: telegram-bot-celery-beat
    environment:
      - DEBUG=${DEBUG:-True}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-telegram_bot_db}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # S3 配置
      - STORAGE_BACKEND=${STORAGE_BACKEND:-local}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - AWS_S3_PUBLIC_READ=${AWS_S3_PUBLIC_READ:-false}
    volumes:
      - .:/app
      - ./storage:/app/storage
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - telegram-bot-network
    restart: unless-stopped
    command: celery -A app.core.celery_app beat --loglevel=info

  # Flower Celery 监控界面（开发环境）
  flower:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: telegram-bot-flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - telegram-bot-network
    restart: unless-stopped
    command: celery -A app.core.celery_app flower --port=5555
    profiles:
      - dev

  # Vue.js 前端开发服务器
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: telegram-bot-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_BOT_NAME=${TELEGRAM_BOT_NAME}
    networks:
      - telegram-bot-network
    restart: unless-stopped
    profiles:
      - dev

  # React 前端生产服务
  frontend:
    build:
      context: ./frontend
    container_name: telegram-bot-frontend
    ports:
      - "3001:80"
    depends_on:
      - api
    networks:
      - telegram-bot-network
    restart: unless-stopped

  # 商品审核Worker服务
  moderation-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: telegram-bot-moderation-worker
    environment:
      - DEBUG=${DEBUG:-True}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-telegram_bot_db}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - API_BASE_URL=http://api:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      # S3 配置
      - STORAGE_BACKEND=${STORAGE_BACKEND:-local}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - AWS_S3_PUBLIC_READ=${AWS_S3_PUBLIC_READ:-false}
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8001:8001"  # 暴露Prometheus指标端口
    depends_on:
      - postgres
      - redis
      - api
    networks:
      - telegram-bot-network
    restart: unless-stopped
    command: python -m app.workers.moderation_worker

  # Prometheus 监控服务
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: telegram-bot-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - telegram-bot-network
    restart: unless-stopped
    depends_on:
      - api
      - moderation-worker

  # Grafana 可视化服务
  grafana:
    image: grafana/grafana:9.5.3
    container_name: telegram-bot-grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - telegram-bot-network
    restart: unless-stopped
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

  # Locust 负载测试服务
  locust:
    image: locustio/locust
    container_name: telegram-bot-locust
    ports:
      - "8089:8089"  # Locust Web UI
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    # 启动命令，指向 API 服务
    command: -f /mnt/locust/locustfile.py --host http://api:8000
    depends_on:
      - api
    networks:
      - telegram-bot-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  telegram-bot-network:
    driver: bridge