# Prometheus 配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'fastapi_api'
    static_configs:
      # 使用服务名 api:8000，因为在Docker网络中可以直接通过服务名访问
      - targets: ['api:8000']

  - job_name: 'moderation_worker'
    static_configs:
      - targets: ['moderation-worker:8001']