"""add moderation_notes to product

Revision ID: 20250905_023521
Revises: 200_product_moderation
Create Date: 2025-09-05 02:35:21.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250905_023521'
down_revision = '200_product_moderation'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('moderation_notes', sa.Text(), nullable=True, comment='AI审核备注'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'moderation_notes')
    # ### end Alembic commands ###